# Generated by Django 5.2.11 on 2026-02-18 17:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.TOKENFORGE_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hex digest of the raw token.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "token_family",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Groups all rotated descendants. Used for replay detection.",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256(IP|UA) at issuance time.",
                        max_length=256,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to the token that replaced this one on rotation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to=settings.TOKENFORGE_TOKEN_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tokenforge_refresh_tokens",
                "abstract": False,
                "swappable": "TOKENFORGE_TOKEN_MODEL",
                "indexes": [
                    models.Index(
                        fields=["user", "revoked"],
                        name="tokenforge__user_id_b26056_idx",
                    ),
                    models.Index(fields=["token_family"], name="tokenforge__token_f_08783f_idx"),
                    models.Index(fields=["expires_at"], name="tokenforge__expires_b9d350_idx"),
                ],
            },
        ),
    ]
